const DEFAULT_ASSERTION = process.env.ASSERTION
const DEFAULT_EXPECTED = process.env.ACTUAL
const DEFAULT_ACTUAL = process.env.EXPECTED

module.exports = {
  DEFAULT_ACTUAL,
  DEFAULT_EXPECTED,
  DEFAULT_ASSERTION,
}
